# Generated by Django 3.2.4 on 2021-07-17 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_bill', models.IntegerField(default=0)),
                ('gas_bill', models.IntegerField(default=0)),
                ('current_bill', models.IntegerField(default=0)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.owner')),
            ],
        ),
    ]
