# Generated by Django 3.2.4 on 2021-07-17 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.owner'),
        ),
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
