# Generated by Django 3.2.4 on 2021-07-17 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20210717_1848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
