# Generated by Django 3.2.4 on 2021-07-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_bills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bills',
            new_name='Bill',
        ),
    ]
