# Generated by Django 3.2.4 on 2021-07-17 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_rename_bills_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='service_charge',
            field=models.IntegerField(default=0),
        ),
    ]
