# Generated by Django 3.2.4 on 2021-07-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20210717_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='extra',
            field=models.IntegerField(default=0),
        ),
    ]
