# Generated by Django 3.2.4 on 2021-07-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_bill_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='flat',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='floor',
            field=models.IntegerField(default=0),
        ),
    ]
