# Generated by Django 3.2.4 on 2021-07-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20210718_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='extracharge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='servicecharge',
            field=models.IntegerField(default=0),
        ),
    ]
